export const Exc = Object.freeze({
    antibac: 'Antibacterial Therapy',
    apache: 'Apache Score',
    age: 'Maximum Age',
    weight: 'Weight Range',
    prevTrial: 'Other Clinical Trial Participation',
    chf: 'Congestive Heart Failure',
    nyha: 'NYHA Class IV or CHF Symptoms at Rest',
    HIV: 'HIV Positive',
    CD4Count: '',
    CD4200: 'CD4 Count <200/µL',
    CD4400: 'CD4 Count <400/µL',
    currentHemaOnco: 'Current Hematologic/Oncologic',
    lungCancer: 'Lung Cancer',
    immunocomp: 'Immunocompromised',
    stemCellTrans: 'Stem Cell Transplant',
    organTrans: 'Solid Organ Transplant',
    dialysis: 'Receiving Dialysis',
    kidneyDisease: 'Chronic Kidney Disease',
    eGFR50: 'eGFR < 50',
    eGFR30: 'eGFR < 30',
    eGFR10: 'eGFR < 10',
    intLungDis: 'Interstitial Lung Disease',
    cystFib: 'Cystic Fibrosis',
    sevHepDysfunction: 'Severe Hepatic Dysfunction',
    seizure: 'Seizure Disorder',
    invMechVent: 'Invasive Mechanical Ventilation', // Todo: come back and fix the rest of these !!!!!!!!!
});
