export const Exc = Object.freeze({
    antibac: 'Antibacterial Therapy',
    apache: 'Apache Score',
    age: 'Maximum Age',
    weight: 'Weight Range',
    prevTrial: 'Participation in Other Clinical Trial',
    chf: 'Congestive Heart Failure',
    nyha: 'NYHA Class IV or CHF Symptoms at Rest',
    HIV: 'HIV Positive',
    CD4Count: 'CD4Count',
    CD4200: 'CD4 Count <200/µL',
    CD4400: 'CD4 Count <400/µL',
    currentHemaOnco: 'Current Hematologic/Oncologic',
    lungCancer: 'Lung Cancer',
    immunocomp: 'Immunocompromised',
    stemCellTrans: 'Stem Cell Transplant',
    organTrans: 'Solid Organ Transplant',
    dialysis: 'Receiving Dialysis',
    kidneyDisease: 'Chronic Kidney Disease',
    eGFR50: 'eGFR < 50',
    eGFR30: 'eGFR < 30',
    eGFR10: 'eGFR < 10',
    intLungDis: 'Interstitial Lung Disease',
    cystFib: 'Cystic Fibrosis',
    sevHepDysfunction: 'Severe Hepatic Dysfunction',
    seizure: 'Seizure Disorder',
    invMechVent: 'Invasive Mechanical Ventilation', // Todo: come back and fix the rest of these !!!!!!!!!
});

export const Exc2 = Object.freeze({
    "Positive_gram_stain_from_lower_repiratory_tract": "Result of gram stain: Positive",
    "Allergy_to_PCN": "Allergy to PCN?",
    "Baseline_Weight": "Weight (kg)",
    "Total_Bilirubin": "Total Bilirubin",
    "Allergy_to_cephalosporin": "Allergy to cephalosporin?",
    "Allergy_to_quinolones": "Allergy to quinolones?",
    "APACHE_II_Score": "APACHE II Score",
    "Corticosteroids_in_past_60_days": "Corticosteroids (> 10mg/d prednisone equivalent > 7-day duration) in past 60 days",
    "Dialysis": "Dialysis",
    "Other_clinical_trial_participation": "Participation in other clinical trial",
    "Invasive_Mechanical_Ventilation": "Invasive Mechanical Ventilation",
    "Cystic_fibrosis": "Cystic fibrosis ",
    "History_Solid_Organ_Transplant": "History of solid organ transplant",
    "Gram_negative_lower_repiratory_tract": "Result of gram stain: Negative",
    "LessThanEqual_24_Hours_Antibacterial_Therapy": "< 24 hours Prior Antibacterial Therapy",
    "APACHE_II_Total_Acute_Physiology_Score": "APACHE II Score",
    "HIV_Infection": "HIV infection",
    "Immune_Compromised": "Immune Compromised",
    "Ventilated_HABP_IMV_lessthan2_days": "Ventilated HABP IMV < 2 days",
    "Chronic_Kidney_Disease": "Chronic kidney disease",
    "VABP_imv_greaterthanequal_2_days": "VABP imv >= 2 days",
    "Immunocompromised_Apache_II_defn": "Immunocompromised (APACHE II definition)",
    "History_of_Seizures": "Seizure disorder",
    "Congestive_Heart_Failure": "Congestive Heart Failure",
    "Positive_blood_sputum_endotracheal_aspirates": "Positive blood or any lower respiratory tract culture result?",
    "eGFR": "eGFR: mL/min/1.73m2 (2009 CKD EPI equation)",
    "Stem_cell_transplant_in_past_12_months": "Stem cell transplant in past 12 months",
    "Age": "Age (Years)",
    "Gram_noresult_lower_repiratory_tract": "Result of gram stain: No Result",
    "Treated_Not_High_Risk_Population": "Treated for suspected nosocomial pneumonia but did not meet not high-risk criteria at enrollment.",
    "Allergy_to_beta-lactam": "Allergy to beta-lactam (specific allergy not specified)?",
    "Microbiologic_sample_collected": "Microbiologic sample collected?",
    "Chemotherapy_administered_in_past_30_days": "Chemotherapy administered in past 30 days",
    "Corticosteroids_at_current_hospitalization": "Corticosteroids (> 10mg/d predisone equivalent > 7-day duration) at current hospitalization",
    "NYHA_Class_IV": "Does patient have congestive heart failure symptoms at rest or documented NYHA Class IV?",
    "Lung_cancer": "Lung cancer",
    "Allergy_to_carbapenem": "Allergy to carbapenem?",
    "High_Risk_Population": "High-risk Population",
    "Severe_hepatic_dysfunction": "Severe hepatic dysfunction",
    "Invasic_mechanical_ventilation_at_time_of_pnuemonia_diagnosis": "Invasive Mechanical Ventilation (IMV), EXPOSURE",
    "CD4 Count": "CD4 Count",
    "Interstitial_lung_disease": "Interstitial lung disease ",
    "Current_Hematologic_Oncologic_Problems": "Current hematologic/oncologic problems",
    "End_stage_renal_disease_(receiving_dialysis)": "End stage renal disease (receiving dialysis)",
    "HABP_with_no_IMV": "HABP with no IMV"
});
